find_package(Curses REQUIRED)
find_package(PAM)

include(CheckFunctionExists)
include(CheckIncludeFiles)

check_include_files(dirent.h HAVE_DIRENT_H)
check_include_files(inttypes.h HAVE_INTTYPES_H)
check_include_files(memory.h HAVE_MEMORY_H)
check_include_files(ndir.h HAVE_NDIR_H)
check_include_files(shadow.h SHADOWPW)
check_include_files(stdint.h HAVE_STDINT_H)
check_include_files(stdlib.h HAVE_STDLIB_H)
check_include_files(string.h HAVE_STRING_H)
check_include_files(strings.h HAVE_STRINGS_H)
check_include_files(stropts.h HAVE_STROPTS_H)
check_include_files(sys/dir.h HAVE_SYS_DIR_H)
check_include_files(sys/ndir.h HAVE_SYS_NDIR_H)
check_include_files(sys/stat.h HAVE_SYS_STAT_H)
check_include_files(sys/types.h HAVE_SYS_TYPES_H)
check_include_files(unistd.h HAVE_UNISTD_H)

check_function_exists(alphasort HAVE_ALPHASORT)
check_function_exists(_exit HAVE__exit)
check_function_exists(fchmod HAVE_FCHMOD)
check_function_exists(fchown HAVE_FCHOWN)
check_function_exists(fdwalk HAVE_FDWALK)
check_function_exists(getcwd HAVE_GETCWD)
check_function_exists(getpt HAVE_GETPT)
check_function_exists(getutent HAVE_GETUTENT)
check_function_exists(lstat HAVE_LSTAT)
check_function_exists(nl_langinfo HAVE_NL_LANGINFO)
check_function_exists(openpty HAVE_OPENPTY)
check_function_exists(rename HAVE_RENAME)
check_function_exists(scandir HAVE_SCANDIR)
check_function_exists(setenv HAVE_SETENV)
check_function_exists(seteuid HAVE_SETEUID)
check_function_exists(setlocale HAVE_SETLOCALE)
check_function_exists(setresuid HAVE_SETRESUID)
check_function_exists(setreuid HAVE_SETREUID)
check_function_exists(strerror HAVE_STRERROR)
check_function_exists(unsetenv HAVE_UNSETENV)
check_function_exists(strftime HAVE_STRFTIME)
check_function_exists(utimes HAVE_UTIMES)
check_function_exists(vsnprintf HAVE_VSNPRINTF)

include(CheckLibraryExists)
check_library_exists(crypt crypt "" HAVE_CRYPT)
if (HAVE_CRYPT)
	find_library(CRYPT_LIBRARY crypt)
	set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} ${CRYPT_LIBRARY})
endif (HAVE_CRYPT)

#check_library_exists(util util "" HAVE_UTIL)
#if (HAVE_UTIL)
#	find_library(UTIL_LIBRARY util)
#	message(set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} ${UTIL_LIBRARY}))
#endif (HAVE_UTIL)

check_library_exists(utempter addToUtmp "" HAVE_UTEMPTER)
if (HAVE_UTEMPTER)
	find_library(UTEMPTER_LIBRARY utempter)
	set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} ${UTEMPTER_LIBRARY})
	set(UTMPOK ON CACHE INTERNAL "" FORCE)
endif (HAVE_UTEMPTER)

if (WITH_SETUID_ROOT)
	set(UTMPOK ON CACHE INTERNAL "" FORCE)
endif (WITH_SETUID_ROOT)

